api/config/routes.rb
Api::Application.routes.draw do
  resources :thermostats

end

api/app/models/thermostat.rb
class Thermostat < ActiveRecord::Base
	validates_presence_of :temperature
end

api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

api/app/controllers/thermostats_controller.rb
class ThermostatsController < ApplicationController
  before_action :set_thermostat, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token 

  # GET /thermostats
  # GET /thermostats.json
  def index
    @thermostats = Thermostat.all
  end

  # GET /thermostats/1
  # GET /thermostats/1.json
  def show
  end

  # GET /thermostats/new
  def new
    @thermostat = Thermostat.new
  end

  # GET /thermostats/1/edit
  def edit
  end

  # POST /thermostats
  # POST /thermostats.json
  def create
    @thermostat = Thermostat.new(thermostat_params)

    if @thermostat.save
      render action: 'show', status: :created, location: @thermostat
    else
      render json: @thermostat.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /thermostats/1
  # PATCH/PUT /thermostats/1.json
  def update
    respond_to do |format|
      if @thermostat.update(thermostat_params)
        format.html { redirect_to @thermostat, notice: 'Thermostat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @thermostat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thermostats/1
  # DELETE /thermostats/1.json
  def destroy
    @thermostat.destroy
    respond_to do |format|
      format.html { redirect_to thermostats_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thermostat
      @thermostat = Thermostat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thermostat_params
      params.require(:thermostat).permit(:serial,:temperature,:humedad,:exterior,:consumoN,:consumoA)
    end
end

api/app/helpers/application_helper.rb
module ApplicationHelper
end

api/app/helpers/thermostats_helper.rb
module ThermostatsHelper
end

api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Api</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

api/app/views/thermostats/_form.html.erb
<%= form_for(@thermostat) do |f| %>
  <% if @thermostat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thermostat.errors.count, "error") %> prohibited this thermostat from being saved:</h2>

      <ul>
      <% @thermostat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :serial %><br>
    <%= f.text_field :serial %>
  </div>
  <div class="field">
    <%= f.label :temperature %><br>
    <%= f.text_field :temperature %>
  </div>
  <div class="field">
    <%= f.label :humedad %><br>
    <%= f.text_field :humedad %>
  </div>
  <div class="field">
    <%= f.label :exterior %><br>
    <%= f.number_field :exterior %>
  </div>
  <div class="field">
    <%= f.label :consumoN %><br>
    <%= f.number_field :consumoN %>
  </div>
  <div class="field">
    <%= f.label :consumoA %><br>
    <%= f.number_field :consumoA %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

api/app/views/thermostats/edit.html.erb
<h1>Editing thermostat</h1>

<%= render 'form' %>

<%= link_to 'Show', @thermostat %> |
<%= link_to 'Back', thermostats_path %>

api/app/views/thermostats/index.html.erb
<h1>Listing thermostats</h1>

<table>
  <thead>
    <tr>
   
      <th>Temperature</th>
      
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @thermostats.each do |thermostat| %>
      <tr>
        <td><%= thermostat.temperature %></td>
        <td><%= link_to 'Show', thermostat %></td>
        <td><%= link_to 'Edit', edit_thermostat_path(thermostat) %></td>
        <td><%= link_to 'Destroy', thermostat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thermostat', new_thermostat_path %>
 <tbody>
    <% @thermostats.each do |thermostat| %>
      <tr>
        <td><%= thermostat.serial %></td>
        <td><%= thermostat.temperature %></td>
        <td><%= thermostat.humedad %></td>
        <td><%= thermostat.exterior %></td>
        <td><%= thermostat.consumoN %></td>
        <td><%= thermostat.consumoA %></td>
        <td><%= link_to 'Show', thermostat %></td>
        <td><%= link_to 'Edit', edit_thermostat_path(thermostat) %></td>
        <td><%= link_to 'Destroy', thermostat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thermostat', new_thermostat_path %>

api/app/views/thermostats/new.html.erb
<h1>New thermostat</h1>

<%= render 'form' %>

<%= link_to 'Back', thermostats_path %>

api/app/views/thermostats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Serial:</strong>
  <%= @thermostat.serial %>
  <strong>Temperature:</strong>
  <%= @thermostat.temperature %>
    <strong>humedad:</strong>
  <%= @thermostat.humedad %>
    <strong>exterior:</strong>
  <%= @thermostat.exterior %>
    <strong>consumoN:</strong>
  <%= @thermostat.consumoN %>
    <strong>consumoA:</strong>
  <%= @thermostat.consumoA %>
</p>

<%= link_to 'Edit', edit_thermostat_path(@thermostat) %> |
<%= link_to 'Back', thermostats_path %>